### ISSUE TITLE
tokenlist class in textrecipes

### ISSUE THREAD

**Issue by EmilHvitfeldt** [krlmlr/awesome-vctrs#5]
I used to have a list of character vectors being moved around a lot, so I ended up giving it a little s3 class wrapper. It is only used internally but does include a print method to stop lagging when printing large lists.

https://github.com/tidymodels/textrecipes
https://tidymodels.github.io/textrecipes/dev/articles/tokenlist.html

**Comment by krlmlr** [comment]
Thanks. Added in d473c2a. Note that `x[0]` and `x[NA]` don't work currently.

``` r
x <- textrecipes::tokenlist(list(letters[1:3], LETTERS[4:6], letters[9:8]))

x[0]
#> Error: `tokens` must be a vector, not NULL.
x[NA]
#> Error: `tokens` must be a vector, not NULL.
```

<sup>Created on 2020-04-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Have you considered wrapping a `new_rcrd()`? This would offload even more code to vctrs.

**Comment by EmilHvitfeldt** [comment]
Thank you! Will look into that bug.

Initially I tried to use `new_rcrd()` but it wouldn't let me put the `pos` and `lemma` as NULL when they weren't used. And moving 3 times the data around when it wasn't needed didn't feel right.

**Comment by krlmlr** [comment]
Perhaps:

```
new_rcrd(purrr::compact(list(x = x, lemma = lemma, pos = pos))

maybe_get_lemma <- function(x) {
  if ("lemma" %in% fields(x)) {
    field(x, "lemma")
  } else {
    NULL
  }
}
```

?

@lionel: If an S3 class wraps a record, do we suggest/require/... that all instances of that class have the same set of fields?

**Comment by EmilHvitfeldt** [comment]
that does seem to work

``` r
library(vctrs)
x <- list(LETTERS[1:4], LETTERS[1:6])
lemma <- NULL
pos <- NULL

aaa <- new_rcrd(purrr::compact(list(x = x, lemma = lemma, pos = pos)))

maybe_get_lemma <- function(x) {
  if ("lemma" %in% fields(x)) {
    field(x, "lemma")
  } else {
    NULL
  }
}

maybe_get_lemma(aaa)
#> NULL
```

<sup>Created on 2020-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So we are basically using `purrr::compact` to avoid creating empty fields.

**Comment by EmilHvitfeldt** [comment]
Thanks for all the help!
I have one last question if you don't mind, what should the expected behavior of 

```r
x <- textrecipes::tokenlist(list(letters[1:3], LETTERS[4:6], letters[9:8]))

x[NA]
```

be?

**Comment by krlmlr** [comment]
What's the representation of an `ǸA` value in your data type? Is it relevant? What happens with NA or empty input?

`textrecipes::tokenlist(list(character()))` perhaps?

**Comment by EmilHvitfeldt** [comment]
I don't think It is really relevant. The empty output should be something this`textrecipes::tokenlist(list(character()))`.  But I don't even know if it would ever be used.

**Comment by krlmlr** [comment]
I guess it's ok to return *anything*, only `vec_size()` must be consistent with the indices.

**Comment by EmilHvitfeldt** [comment]
I'm not getting `vec_size()` consistancy right now with `NA`.

``` r
library(textrecipes)
tkn_list <- tokenlist(list(letters, LETTERS))

tkn_list[NA]
#> <textrecipes_tokenlist[2]>
#> [1] [0 tokens] [0 tokens]
#> # Unique Tokens: 0
vctrs::vec_size(tkn_list[NA])
#> [1] 2
```

<sup>Created on 2020-04-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

What method do I need to modify to fix this?

**Comment by krlmlr** [comment]
This is correct, `NA` expands to `rep(NA, 2)`. Should work with `NA_integer_`?

**Comment by EmilHvitfeldt** [comment]
oh okay, perfect! I guess I never knew what happened when you subset by NA. Then everything is working as intended. The repo is updated to use `new_rcrd()`.

Thank you so much for your help and time!
